### ISSUE TITLE
Specify constraints for using specific combinations of GO terms and relations

### ISSUE THREAD

**Issue by vanaukenk** [geneontology/go-shapes#166]
Following on from discussions about what relations to allow in GO-CAMs and ShEx:

We need to specify the domain and range constraints for use of specific relations with specific GO terms, e.g. cell morphogenesis 'results in morphogenesis of' motor neuron.

This ticket will be used to draft this list for further discussion on the GO-CAM specifications call.

**Comment by vanaukenk** [comment]
Possible representation in ShEx for use of 'acts on population of'.  Note that 'acts on population of' is still a gorel, though.  Do we also need negation shapes?

PREFIX GoCellPopulationProliferation: \<http://purl.obolibrary.org/obo/GO_0008283>
PREFIX GoHomeostasisOfNumberOfCells: \<http://purl.obolibrary.org/obo/GO_0048872>
PREFIX acts_on_population_of: \<http://purl.obolibrary.org/obo/RO_???????>

\<CellPopulationProliferationClass> IRI @\<OwlClass> AND EXTRA rdfs:subClassOf {
  rdfs:subClassOf [ GoCellPopulationProliferation: ];

}

\<CellPopulationProliferation> @\<GoCamEntity> AND EXTRA a {
 a @\<CellPopulationProliferationClass>; {1}
acts_on_population_of: @\<AnatomicalEntity> {0,1};
} // rdfs:comment  "a cell population proliferation GO biological process or child”



\<HomeostasisOfNumberOfCellsClass> IRI @\<OwlClass> AND EXTRA rdfs:subClassOf {
  rdfs:subClassOf [ GoHomeostasisOfNumberOfCells: ];

}

\<HomeostasisOfNumberOfCells> @\<GoCamEntity> AND EXTRA a {
 a @\<HomeostasisOfNumberOfCellsClass>; {1}
acts_on_population_of: @<AnatomicalEntity> {0,1};
} // rdfs:comment  "a homeostasis of number of cells GO biological process or child”

**Comment by goodb** [comment]
@vanaukenk continuing discussion from spec call yesterday.  If we did want to go down the road proposed here as many on the call seemed to like, we would need to add additional lines to the [shapemap file](https://github.com/geneontology/go-shapes/blob/master/shapes/go-cam-shapes.shapeMap) along the lines of:
SPARQL 'SELECT ?x WHERE { ?x a/<http://www.w3.org/2000/01/rdf-schema#subClassOf> <http://purl.obolibrary.org/obo/GO_0008283> }' @ <http://purl.obolibrary.org/obo/go/shapes/CellPopulationProliferation>

It also seems like you'd want to change
`<CellPopulationProliferation> @<GoCamEntity>`
to
`<CellPopulationProliferation> @<BiologicalProcess>`

so that you would also get the rest of the BP constraints on those nodes.  

If there are specific constellations of properties that we want to enforce are only associated with specific subclasses of our go-cam roots, I think something like this is needed.  

I think again, we need to sort out how the shex constraints relate to the ontology constraints.  If we define the domain and range of e.g. acts_on_population_of in the RO to apply to the classes listed here, then what we are doing here is not really necessary - or could be computed automatically from the ontology.

**Comment by ukemi** [comment]
Is there a way to leverage the DOS-DPs to do this?

**Comment by goodb** [comment]
@ukemi if you mean compute shapes corresponding to logical definitions, then I don't think DOS-DPs would work on a technical level.  That is really for taking a spreadsheet and turning it into axioms.  Intention-wise, yes, thats the idea.  

We could use the OWL-API to do it.  I don't think it would be a problem.  But..  its not clear to me if its a good idea or not.  Why be redundant?  I guess if the shapes were really driving things - e.g. automatic form generation for the UI, then it would be a way to make sure everyone was in sync and to let the ontology drive the process.

**Comment by vanaukenk** [comment]
Closing this ticket, as we've added many term-specific BP shapes.
