### ISSUE TITLE
Need to decide on valid entity types and corresponding shapes

### ISSUE THREAD

**Issue by vanaukenk** [geneontology/go-shapes#173]
I am combining tickets #26 #31 #50 into this one, new ticket.

Models fail validation, I believe, because the entity types do not match what is in the ShEx.

![image](https://user-images.githubusercontent.com/1730534/72167685-9d485e80-3399-11ea-900b-e1266c71d96f.png)

![image](https://user-images.githubusercontent.com/1730534/72167768-c8cb4900-3399-11ea-8c43-64ad3788d264.png)

In the gpi 2.0 specs, we propose using SO terms to define entity types, although we know that this doesn't cover protein-containing complexes and we need a GO term for that.

I am wondering if we need to add to, or replace, ChEBI's information biomacromolecule in the ShEx with SO term(s).

@balhoff @goodb 

See also:  https://github.com/geneontology/go-annotation/issues/2740

**Comment by goodb** [comment]
@vanaukenk could you share the .ttl file for the model shown there?  Or just send me a link?

That looks like a problem with the validator.  In the json there, I see an inferred type of CHEBI_33695  which should line up with InformationBiomacromolecule in the shex schema and validate.  This sounds familiar - its possible I have something locally that fixes it that hasn't been made live.

**Comment by vanaukenk** [comment]
Thanks @goodb 

This is the test model I made:
http://noctua-dev.berkeleybop.org/editor/graph/gomodel:5df94d0c00000005

**Comment by goodb** [comment]
@vanaukenk I believe this PR should fix the problem: https://github.com/geneontology/go-shapes/pull/174  

@kltm once the PR is accepted, we will need a noctua-dev restart.  (Any of us can accept the PR any time, all tests are good.  but I hoped @balhoff might have a look in case it raises other questions).

**Comment by goodb** [comment]
Okay merged.  ready for noctua-dev restart.

**Comment by goodb** [comment]
Didn't mean to close..  opening up for @vanaukenk to close if she chooses.  
It looks like the restart blew up the test model.  I made another one and things are looking good:
http://noctua-dev.berkeleybop.org/editor/graph/gomodel:5e18e83800000000  

Note that the chemokine binding node is red because a function is not allowed to regulate a process - (a control to show that the shex test is running).  Take away that negatively regulates relation and the model should validate.  

![Screen Shot 2020-01-10 at 1 33 07 PM](https://user-images.githubusercontent.com/2086122/72187936-e4404f00-33ad-11ea-91a4-4b64406ec2ae.png)

**Comment by vanaukenk** [comment]
Thanks for the fix @goodb 
The validation for entity types looks good.  I added a ncRNA and a protein-containing complex to the test model for good measure, and they validate, as well.
