### ISSUE TITLE
Add CC 'part of' CC

### ISSUE THREAD

**Issue by vanaukenk** [geneontology/go-shapes#23]
`<CellularComponent>  @<AnatomicalEntity>` AND {
   bl:category [GoCellularComponent:]  ;
   part_of: `@<CellularComponent>` {0,1};
   part_of: `@<Cell>` {0,1};  
  allow direct pass-through for single-cell organisms"   
   part_of: @<Organism> {0,1};  
} // rdfs:comment  "a cellular component"

**Comment by cmungall** [comment]
What are the use cases for recursive CC-po-CC? For things like a chromosome in the mitochondrion we already have precomposed terms

**Comment by pgaudet** [comment]
Protein-containing complex in organelle ?

**Comment by vanaukenk** [comment]
Adding another use case that is coming from SynGO annotations:

UniProtKB	A0A0K3AR90	part_of	GO:0098674 (extrinsic component of neuronal dense core vesicle membrane)	PMID:17881523	ECO:0006003			20180711	SynGO	part_of(GO:0031594 - neuromuscular junction),part_of(UBERON:0000061 - anatomical structure)	go_evidence=IDA

Use of UBERON here is a separate issue....

**Comment by pgaudet** [comment]
Is there an inconsistency here? The neuromuscular junction is not part of the cell (in fact should it even be 'extracellular'? 
Are they trying to say 'extrinsic component of neuronal dense core vesicle membrane' adjacent_to ' neuromuscular junction'? 

Or perhaps since the  dense core vesicle goes from inside to outside the cell, it cannot be part_of the cell ? I thought the vesicle never crossed the boundary of the cell, but that the membrane fused.  

![image](https://user-images.githubusercontent.com/4782928/61439915-b4eedf00-a942-11e9-944c-6e08b3e93f70.png)


Pascale

**Comment by ukemi** [comment]
Since things like cell junctions and synapses span more than one cell, they are not part_of any single cell. For the MGI annotation extensions that refer to >1 cell and correspond to cell junctions, I have changed the part_of relation to overlaps.

**Comment by ukemi** [comment]
Presumably the neuromuscular junction contains the presynaptic membrane on the neuron, the synaptic cleft and the postsynaptic membrane on the muscle cell.
There is no asserted link from the dense core vesicle and the synapse because according to the definition, the vesicles can be found in a variety of places. This seems to me to be a legitimate use of CC part_of CC where the curators would like to specify an instance of the vesicle as part of the neuromuscular junction. If we do not allow this kind of post-composition, we will need to pre-compose all of these terms.

**Comment by vanaukenk** [comment]
I'm going to re-open this issue because I don't think we've fully addressed extracellular components wrt their relationship to cells, particularly if curators want to capture different cell types bounding an extracellular structure.

**Comment by dustine32** [comment]
@vanaukenk @ukemi @cmungall I have a `CC-part_of->CC` example from the MOD imports that may interest you. A GPAD line:
```
MGI     MGI:1336882     part_of GO:0042588      MGI:MGI:3801544|PMID:18535671   ECO:0000314                     20160406        MGI part_of(EMAPA:35651),part_of(CL:0002064),part_of(GO:1990794)|part_of(EMAPA:35651),part_of(CL:0002064),part_of(GO:0045178)
```
Part of the extension (`part_of(EMAPA:35651),part_of(CL:0002064),part_of(GO:0045178)`) is going to be translated to:
```
MGI:MGI:1336882-located_in->GO:0042588-part_of->GO:0045178->...
```
According to discussion in https://github.com/geneontology/gocamgen/issues/25. With `GO:0042588` being "zymogen granule" and `GO:0045178` being "basal part of cell", does this translation to `CC-part_of->CC` make sense?

**Comment by ukemi** [comment]
Hi @dustine32. In general this kind of situation should be allowed. In this case, the annotation indicates that the granule is part_of the basal part of a cell. The only other alternative would be to say that the granule is located_in the basal part of the cell. I think this relation between components would lead to curator confusion.

**Comment by ukemi** [comment]
Do we have the chain located_in-o-part_of->located_in? I don't see it when I load go-edit.obo.

**Comment by balhoff** [comment]
We don't. Also, it is not in RO. @cmungall is that just an oversight?

**Comment by dustine32** [comment]
Thanks @ukemi ! I have a sweet pic in https://github.com/geneontology/gocamgen/issues/25#issuecomment-537136980 of how I'm translating this right now.

**Comment by cmungall** [comment]
oversight

**Comment by vanaukenk** [comment]
We have that CC can be 'part of' Anatomical Entity, so I think the original issue is addressed.
