### ISSUE TITLE
Handling interacting taxon data - has_input to the relevant BP?

### ISSUE THREAD

**Issue by vanaukenk** [geneontology/go-shapes#237]
In WB, we have a number of annotations to terms like 'defense response to Gram negative bacterium' where we've indicated the specific type of bacteria in the interacting taxon field of the GPAD file.

For GO-CAMs, we could capture this as an input to the BP, e.g. 'has input' NCBITaxon:287, but we'd need to update the BP shape to do this.

@ukemi @dustine32 @thomaspd @pgaudet @cmungall @goodb 

Any thoughts on, or objections to, handling interacting taxa data this way?

**Comment by ukemi** [comment]
Is an NCBITaxon an organism? We have a few annotations like this too if I remember correctly.

**Comment by vanaukenk** [comment]
This is what we currently have declared at the top of the ShEx:

PREFIX GoOrganism: <http://purl.obolibrary.org/obo/NCBITaxon_1>

**Comment by vanaukenk** [comment]
From 2020-09-29 call:

We discussed on the GO-CAM specifications call whether 'has input' really is the best relation for a process that involves another organism, like 'defense response to Gram negative bacterium'.

Perhaps a new RO relation that is a sibling to 'has input' would be better, but we need to come up with a good definition.

Note that BP terms like 'defense response to x organism' are currently not logically defined in the ontology.

Will add this ticket as an agenda item to the next ontology call.

**Comment by pgaudet** [comment]
There are a number of existing relations that could work: 

'symbiotically interacts with'
'host of'
'has pathogen'
'parasitized by'

Thanks, Pascale

**Comment by vanaukenk** [comment]
Here's the hierarchy of the above relations in RO:

![image](https://user-images.githubusercontent.com/1730534/96463977-4b204d80-11f5-11eb-827b-daf92aaef17e.png)

I have questions about the meaning of 'symbiotically' in the context of a defense response, given how its' usage is described in the comment, i.e. 'mutualism through parasitism'.

We can discuss further on the ontology call.

**Comment by ValWood** [comment]
This aligns with the solution me and my PHI-Base colleagues have been angling for.

https://github.com/geneontology/go-ontology/issues/19430
(and lots of related problems with these terms noted in other tickets, mainly about problems related to  aligning other terms with this branch).
We have a big issue with the "response to organism terms"  anyway because  people are using these instead of the appropriate   process describing the interaction under this branch
https://www.ebi.ac.uk/QuickGO/term/GO:0051702
--https://www.ebi.ac.uk/QuickGO/term/GO:0051851

I would say we should take this further and have only 'defense response to symbiont' (or host) and all the rest of the species information should be done via a taxon relationship. Otherwise the ontology is difficult to navigate and maintain. 

Also, the defenses are largely similar, or overlapping- molecules are recognised (usually carbohydrates, or glycoproteins) not species. The processes these molecules activate are the same, but we end up with kingdom, or domain, family specific processes to describe the same thing).

**Comment by pgaudet** [comment]
I agree - also it would help keep terms not relevant to the scope of GO out of the ontology.

**Comment by pgaudet** [comment]
Decision on the ontology call is to keep using has_input - until we come up with a better solution. 

Has input implies that there is a change in the input - but this is usually the case, different gene products are being expressed during the response.

**Comment by vanaukenk** [comment]
@dustine32 

For an imported annotation that looks like this in the GPAD:

WB:WBGene00003374	RO:0002331	GO:0050829	PMID:25274306|WB_REF:WBPaper00045829	ECO:0000316	WB:WBGene00004978	NCBITaxon:287	2017-03-10	WB	id=GOA:2114107133|comment=go_evidence:IGI

This is what the resulting imported annotation would look like in Noctua:

![image](https://user-images.githubusercontent.com/1730534/97341073-fadf6600-185a-11eb-9150-d5212a78b88e.png)

**Comment by dustine32** [comment]
Thanks @vanaukenk ! As you can see, I made a ticket here: https://github.com/geneontology/gocamgen/issues/85

**Comment by vanaukenk** [comment]
The ShEx has been updated, so I'm closing this ticket.

We can continue to track progress on the [related gocamgen ticket](https://github.com/geneontology/gocamgen/issues/85).
